create database if not exists renewable_energy_project; USE renewable_energy_project;


CREATE TABLE plant_master (
    plant_id INT PRIMARY KEY,
    plant_name VARCHAR(255),
    country VARCHAR(100),
    plant_type VARCHAR(100),
    capacity_mw FLOAT,
    installation_year INT,
    operator_company VARCHAR(255)
);

CREATE TABLE energy_generation (
    generation_id BIGINT PRIMARY KEY,
    plant_id INT,
    datetime DATETIME,
    energy_generated_mwh FLOAT,
    downtime_minutes INT,
    efficiency_percent FLOAT
);

CREATE TABLE sensor_readings (
    sensor_id BIGINT PRIMARY KEY,
    plant_id INT,
    timestamp DATETIME,
    temperature FLOAT,
    vibration_level FLOAT,
    voltage FLOAT,
    humidity FLOAT
);

CREATE TABLE maintenance_logs (
    maintenance_id BIGINT PRIMARY KEY,
    plant_id INT,
    maintenance_type VARCHAR(100),
    issue_severity VARCHAR(50),
    maintenance_cost FLOAT,
    downtime_hours FLOAT,
    maintenance_date DATE
);

CREATE TABLE energy_sales (
    sale_id BIGINT PRIMARY KEY,
    plant_id INT,
    customer_type VARCHAR(100),
    energy_sold_mwh FLOAT,
    revenue_usd FLOAT,
    sale_date DATE
);

CREATE TABLE weather_data (
    weather_id BIGINT PRIMARY KEY,
    country VARCHAR(100),
    timestamp DATETIME,
    wind_speed FLOAT,
    sunlight_hours FLOAT,
    rainfall_mm FLOAT,
    temperature FLOAT
);

CREATE TABLE carbon_credits (
    credit_id BIGINT PRIMARY KEY,
    plant_id INT,
    credits_generated FLOAT,
    market_price_usd FLOAT,
    transaction_date DATE
);

CREATE TABLE grid_failures (
    failure_id BIGINT PRIMARY KEY,
    plant_id INT,
    failure_type VARCHAR(100),
    outage_hours FLOAT,
    financial_loss_usd FLOAT,
    failure_date DATE
);

Select Count(*) From grid_failures;
Select Count(*) From carbon_credits;
Select Count(*) From energy_sales;
Select Count(*) From sensor_readings;
Select Count(*) From weather_data;
Select Count(*) From maintenance_logs;
Select Count(*) From plant_master;
Select Count(*) From energy_generation;

DESC energy_generation;

-- 1. Find total energy generated by each plant.
SELECT 
    pm.country,
    pm.plant_type,
    pm.plant_name,
    ROUND(SUM(eg.energy_generated_mwh), 2) AS total_energy_generated_mwh
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
GROUP BY 
    pm.country,
    pm.plant_type,
    pm.plant_name
ORDER BY total_energy_generated_mwh DESC;

-- 2. Find top 10 plants with highest efficiency.
SELECT 
    pm.plant_id,
    pm.plant_name,
    pm.plant_type,
    pm.country,
    ROUND(AVG(eg.efficiency_percent), 2) AS avg_efficiency_percent
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
GROUP BY 
    pm.plant_id,
    pm.plant_name,
    pm.plant_type,
    pm.country
ORDER BY avg_efficiency_percent DESC
LIMIT 10;

-- 3. Calculate total revenue generated country-wise.
SELECT 
    pm.country,
    ROUND(SUM(es.revenue_usd), 2) AS total_revenue_usd
FROM plant_master pm
JOIN energy_sales es
    ON pm.plant_id = es.plant_id
GROUP BY pm.country
ORDER BY total_revenue_usd DESC;

-- 4. Find plants with downtime greater than 100 hours.
SELECT 
    pm.plant_id,
    pm.plant_name,
    pm.country,
    ROUND(SUM(eg.downtime_minutes) / 60, 2) AS total_downtime_hours
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
GROUP BY 
    pm.plant_id,
    pm.plant_name,
    pm.country
HAVING SUM(eg.downtime_minutes) / 60 > 100
ORDER BY total_downtime_hours DESC;

-- 5. Find average maintenance cost by maintenance type.
SELECT 
    maintenance_type,
    ROUND(AVG(maintenance_cost), 2) AS avg_maintenance_cost_usd
FROM maintenance_logs
GROUP BY maintenance_type
ORDER BY avg_maintenance_cost_usd DESC;

-- 6. Find monthly energy generation trend for each country.
SELECT 
    pm.country,
    YEAR(eg.datetime) AS year,
    MONTH(eg.datetime) AS month,
    ROUND(SUM(eg.energy_generated_mwh), 2) AS total_energy_generated_mwh
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
GROUP BY 
    pm.country,
    YEAR(eg.datetime),
    MONTH(eg.datetime)
ORDER BY 
    pm.country,
    year,
    month;
    
-- 7. Identify plants whose efficiency dropped below 60%.
SELECT DISTINCT
    pm.plant_id,
    pm.plant_name,
    pm.country,
    pm.plant_type
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
WHERE eg.efficiency_percent < 60
ORDER BY pm.plant_name;

-- 8. Find top 5 countries generating highest carbon credits.
SELECT 
    pm.country,
    ROUND(SUM(cc.credits_generated), 2) AS total_carbon_credits
FROM plant_master pm
JOIN carbon_credits cc
    ON pm.plant_id = cc.plant_id
GROUP BY pm.country
ORDER BY total_carbon_credits DESC
LIMIT 5;

-- 9. Calculate yearly revenue growth percentage.
WITH yearly_revenue AS (
    SELECT
        YEAR(sale_date) AS sales_year,
        SUM(revenue_usd) AS total_revenue
    FROM energy_sales
    GROUP BY YEAR(sale_date)
)
SELECT
    sales_year,
    ROUND(total_revenue, 2) AS total_revenue_usd,
    ROUND(
        (
            (total_revenue -
             LAG(total_revenue) OVER (ORDER BY sales_year))
            /
            LAG(total_revenue) OVER (ORDER BY sales_year)
        ) * 100,
        2
    ) AS revenue_growth_percentage
FROM yearly_revenue
ORDER BY sales_year;


-- 10. Find plants having more than 3 grid failures in a month.
SELECT
    pm.plant_id,
    pm.plant_name,
    YEAR(gf.failure_date) AS year,
    MONTH(gf.failure_date) AS month,
    COUNT(gf.failure_id) AS total_failures
FROM plant_master pm
JOIN grid_failures gf
    ON pm.plant_id = gf.plant_id
GROUP BY
    pm.plant_id,
    pm.plant_name,
    YEAR(gf.failure_date),
    MONTH(gf.failure_date)
HAVING COUNT(gf.failure_id) > 3
ORDER BY total_failures DESC;

-- 11. Calculate average temperature impact on solar energy generation.
SELECT
    CASE
        WHEN wd.temperature < 20 THEN 'Below 20°C'
        WHEN wd.temperature BETWEEN 20 AND 30 THEN '20-30°C'
        WHEN wd.temperature BETWEEN 31 AND 40 THEN '31-40°C'
        ELSE 'Above 40°C'
    END AS temperature_range,
    ROUND(AVG(eg.energy_generated_mwh), 2) AS avg_energy_generated_mwh
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
JOIN weather_data wd
    ON pm.country = wd.country
    AND DATE(eg.datetime) = DATE(wd.timestamp)
WHERE pm.plant_type = 'Solar'
GROUP BY temperature_range
ORDER BY temperature_range;

-- 12. Find cumulative revenue generated by each plant.
SELECT
    pm.plant_id,
    pm.plant_name,
    es.sale_date,
    es.revenue_usd,
    ROUND(
        SUM(es.revenue_usd) OVER (
            PARTITION BY pm.plant_id
            ORDER BY es.sale_date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS cumulative_revenue_usd
FROM plant_master pm
JOIN energy_sales es
    ON pm.plant_id = es.plant_id
ORDER BY
    pm.plant_id,
    es.sale_date;
    
-- 13. Find most expensive maintenance issue category.
SELECT
    maintenance_type,
    ROUND(SUM(maintenance_cost), 2) AS total_maintenance_cost_usd
FROM maintenance_logs
GROUP BY maintenance_type
ORDER BY total_maintenance_cost_usd DESC
LIMIT 1;

-- 14. Find correlation between downtime and revenue loss.
SELECT
    pm.plant_id,
    pm.plant_name,
    ROUND(SUM(gf.outage_hours), 2) AS total_downtime_hours,
    ROUND(SUM(gf.financial_loss_usd), 2) AS total_revenue_loss_usd
FROM plant_master pm
JOIN grid_failures gf
    ON pm.plant_id = gf.plant_id
GROUP BY
    pm.plant_id,
    pm.plant_name
ORDER BY total_revenue_loss_usd DESC;

-- 15. Identify plants operating above 95% efficiency continuously for 30 days.
SELECT
    pm.plant_id,
    pm.plant_name,
    COUNT(DISTINCT DATE(eg.datetime)) AS days_above_95
FROM plant_master pm
JOIN energy_generation eg
    ON pm.plant_id = eg.plant_id
WHERE eg.efficiency_percent > 95
GROUP BY
    pm.plant_id,
    pm.plant_name
HAVING COUNT(DISTINCT DATE(eg.datetime)) >= 30
ORDER BY days_above_95 DESC;

--  16. Rank plants within each country based on profitability.
WITH sales_revenue AS (
    SELECT
        plant_id,
        SUM(revenue_usd) AS sales_revenue
    FROM energy_sales
    GROUP BY plant_id
),
carbon_revenue AS (
    SELECT
        plant_id,
        SUM(credits_generated * market_price_usd) AS carbon_revenue
    FROM carbon_credits
    GROUP BY plant_id
),
maintenance_cost AS (
    SELECT
        plant_id,
        SUM(maintenance_cost) AS maintenance_cost
    FROM maintenance_logs
    GROUP BY plant_id
),
failure_loss AS (
    SELECT
        plant_id,
        SUM(financial_loss_usd) AS failure_loss
    FROM grid_failures
    GROUP BY plant_id
)
SELECT
    pm.country,
    pm.plant_id,
    pm.plant_name,

    ROUND(
        COALESCE(sr.sales_revenue,0)
        + COALESCE(cr.carbon_revenue,0)
        - COALESCE(mc.maintenance_cost,0)
        - COALESCE(fl.failure_loss,0),
        2
    ) AS net_profit_usd,

    DENSE_RANK() OVER (
        PARTITION BY pm.country
        ORDER BY
        (
            COALESCE(sr.sales_revenue,0)
            + COALESCE(cr.carbon_revenue,0)
            - COALESCE(mc.maintenance_cost,0)
            - COALESCE(fl.failure_loss,0)
        ) DESC
    ) AS profitability_rank

FROM plant_master pm
LEFT JOIN sales_revenue sr
    ON pm.plant_id = sr.plant_id
LEFT JOIN carbon_revenue cr
    ON pm.plant_id = cr.plant_id
LEFT JOIN maintenance_cost mc
    ON pm.plant_id = mc.plant_id
LEFT JOIN failure_loss fl
    ON pm.plant_id = fl.plant_id

ORDER BY
    pm.country,
    profitability_rank;
    
-- 17. Detect anomaly periods where sensor vibration exceeded normal threshold.
SELECT
    pm.plant_id,
    pm.plant_name,
    sr.timestamp,
    sr.vibration_level
FROM sensor_readings sr
JOIN plant_master pm
    ON sr.plant_id = pm.plant_id
WHERE sr.vibration_level > 8
ORDER BY sr.vibration_level DESC;

-- 18. Find predictive maintenance indicators using sensor readings.
SELECT
    pm.plant_id,
    pm.plant_name,
    sr.timestamp,
    sr.temperature,
    sr.vibration_level,
    sr.voltage,
    sr.humidity
FROM sensor_readings sr
JOIN plant_master pm
    ON sr.plant_id = pm.plant_id
WHERE sr.temperature > 80
   OR sr.vibration_level > 8
   OR sr.voltage < 200
   OR sr.humidity > 90
ORDER BY sr.timestamp DESC;

-- 19. Create rolling 7-day average energy production trend.
WITH daily_generation AS (
    SELECT
        DATE(datetime) AS generation_date,
        SUM(energy_generated_mwh) AS daily_energy_generated
    FROM energy_generation
    GROUP BY DATE(datetime)
)
SELECT
    generation_date,
    daily_energy_generated,
    ROUND(
        AVG(daily_energy_generated) OVER (
            ORDER BY generation_date
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS rolling_7_day_avg_mwh
FROM daily_generation
ORDER BY generation_date;

-- 20. Build a complete profitability report: